name: Run Unit Tests CI
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: set up Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          java-version: 1.8
          distribution: 'zulu'


      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        
      # Execute unit tests
      - name: Tests
        run: ./gradlew test --stacktrace

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
